---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>
  binary: <%= ENV['DOCKER_BINARY'] %>
  privileged: true

provisioner:
  name: chef_solo
  environments_path: 'files/default/test/environments'

platforms:
  - name: ubuntu-12.04
    driver_config:
      require_chef_omnibus: latest
  - name: ubuntu-14.04
    driver_config:
      require_chef_omnibus: latest

suites:
  - name: default
    provisioner:
      solo_rb:
        environment: integration

    run_list:
      - recipe[runnable_base]
      - recipe[runnable_api-server::mongodb]
      - recipe[runnable_base::redis]
      - recipe[runnable_api-server::default]
      - recipe[minitest-handler]
    attributes:

  - name: mongodb
    provisioner:
      solo_rb:
        environment: integration

    run_list:
      - recipe[runnable_api-server::mongodb]
      - recipe[minitest-handler]
    attributes:

  - name: redis
    provisioner:
      solo_rb:
        environment: integration

    run_list:
      - recipe[runnable_base::redis]
      - recipe[minitest-handler]
    attributes:
