source 'https://api.berkshelf.com'

metadata

cookbook 'runnable_nodejs', git: 'git@github.com:CodeNow/runnable_nodejs-cookbook.git'

cookbook 'apt', github: 'opscode-cookbooks/apt'

cookbook 'minitest-handler', github: 'btm/minitest-handler-cookbook'
